version: '3.9'

services:
  customer-service:
    build:
      context: .
      dockerfile: docker/customer-service/Dockerfile
    container_name: customer
    ports:
      - '3002:3002' # HTTP API
      - '50051:50051' # gRPC
    networks:
      - comcore_net

  order-service:
    build:
      context: .
      dockerfile: docker/order-service/Dockerfile
    container_name: order
    ports:
      - '3001:3001'
    networks:
      - comcore_net

  jobs-service:
    build:
      context: .
      dockerfile: docker/jobs-service/Dockerfile
    container_name: jobs
    ports:
      - '3003:3003'
    depends_on:
      - redis
      - customer-service
    networks:
      - comcore_net

  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    container_name: web
    ports:
      - '3000:80' # expose nginx on host: http://localhost:3000
    depends_on:
      - customer-service
      - order-service
      - redis
    networks:
      - comcore_net
    restart: always

  ### Redis Container ###
  redis:
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
    container_name: redis
    volumes:
      - ./local_data_saved/redis:/data
    ports:
      - '16379:6379'
    networks:
      - comcore_net

networks:
  comcore_net:
    driver: bridge
