version: '3.9'

services:
  customer-service:
    build:
      context: .
      dockerfile: docker/customer-service/Dockerfile
    image: comcore4/customer-service:dev
    container_name: comcore4_customer_service
    ports:
      - '9002:9002' # optional; internal services are reachable by nginx via service name
    networks:
      - comcore_net

  order-service:
    build:
      context: .
      dockerfile: docker/order-service/Dockerfile
    image: comcore4/order-service:dev
    container_name: comcore4_order_service
    ports:
      - '9001:9001'
    networks:
      - comcore_net

  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    image: comcore4/web:dev
    container_name: comcore4_web
    ports:
      - '8080:80' # expose nginx on host: http://localhost:8080
    depends_on:
      - customer-service
      - order-service
    networks:
      - comcore_net
    restart: always

  ### Redis Container ###
  redis:
    build:
      context: ./
      dockerfile: ./docker/redis/Dockerfile
    volumes:
      - ./local_data_saved/redis:/data
    ports:
      - '16379:6379'
    networks:
      - comcore_net

networks:
  comcore_net:
    driver: bridge
